version: "3.8"

volumes:
  db-store:

services:

  app:
    build: ./docker_files/php
    volumes:
      - ./backend:/var/www

  web:
    image: nginx:1.18-alpine
    ports:
      - 8080:80
    volumes:
      - ./backend:/var/www
      - ./docker_files/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
  
  db:
    build: ./docker_files/mysql
    volumes:
      - db-store:/var/lib/mysql


  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: 'db'  
    ports:
      - '127.0.0.1:12080:80'


